# Basic Linear Algebra in Julia

Author: Andreas Noack Jensen (MIT) (http://www.econ.ku.dk/phdstudent/noack/) (with edits from Jane Herriman)

In [1]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 4  4  3
 3  3  4
 4  3  4

In [2]:
B = A
C = copy(A)
[B C]

3×6 Matrix{Int64}:
 4  4  3  4  4  3
 3  3  4  3  3  4
 4  3  4  4  3  4

In [4]:
# Watch out!
A[1] = 17
[B C] # B and A are references to the same memory 

3×6 Matrix{Int64}:
 17  4  3  4  4  3
  3  3  4  3  3  4
  4  3  4  4  3  4

---

In [5]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

### Multiplication

In [6]:
b = A*x

3-element Vector{Float64}:
 24.0
 10.0
 11.0

### Transposition

In [7]:
Asym = A + A'

3×3 Matrix{Int64}:
 34  7  7
  7  6  7
  7  7  8

### Transposed multiplication

In [8]:
Apd = A'A

3×3 Matrix{Int64}:
 314  89  79
  89  34  36
  79  36  41

#### Solving linear systems

The problem $Ax = b$ for square $A$ is solved by the `\` function

In [9]:
A\b

3-element Vector{Float64}:
 1.0
 1.0000000000000004
 1.0

#### Overdetermined systems
When A is tall the \ function calculates the least squares solution.

In [11]:
# Keep all rows and only the first 2 columns of `A`
Atall = A[:, 1:2]
display(Atall)
Atall\b

3×2 Matrix{Int64}:
 17  4
  3  3
  4  3

2-element Vector{Float64}:
 0.8119782214156079
 2.550998185117967

The \ function also works for rank deficient least squares problems. In this case, the least squares solution is not unique and Julia returns the solution with smallest norm.

In [12]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.804609  0.394465  0.811
 0.597432  0.190244  0.313571
 0.123782  0.920277  0.865329

In [14]:
[A[:, 1] A[:, 1]] \ b

2-element Vector{Float64}:
 13.066599313007636
 13.066599313007641

### Underdetermined systems
When A is short the \ function returns the minimum norm solution

In [15]:
Ashort = A[1:2, :]
display(Ashort)
Ashort \ b[1:2]

2×3 Matrix{Float64}:
 0.804609  0.394465  0.811
 0.597432  0.190244  0.313571

3-element Vector{Float64}:
  1.3678852343140524
  8.715407773714078
 23.99688510304585